[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
  framework = "create-react-app"

[functions]
  directory = "frontend/netlify/functions"

[build.environment]
  NODE_VERSION = "18"  # or "20" if you're using Node 20
